// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapNhom11.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221130044912_TheLoai")]
    partial class TheLoai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BaiTapNhom11.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("BaiTapNhom11.Models.KhoSach", b =>
                {
                    b.Property<string>("TenSach")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConLai")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaBan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("TEXT");

                    b.HasKey("TenSach");

                    b.ToTable("KhoSach");
                });

            modelBuilder.Entity("BaiTapNhom11.Models.TheLoai", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoai");
                });
#pragma warning restore 612, 618
        }
    }
}
