// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapNhom11.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221130043437_KhoSach")]
    partial class KhoSach
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BaiTapLon_Nhom11.Models.KhoSach", b =>
                {
                    b.Property<string>("TenSach")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConLai")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaBan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("TEXT");

                    b.HasKey("TenSach");

                    b.ToTable("KhoSach");
                });
#pragma warning restore 612, 618
        }
    }
}
